# 丘멆잺 IMPORTANTE: Esta aplicaci칩n NO es compatible con Netlify
#
# Esta es una aplicaci칩n FastAPI (backend Python) que requiere:
# - Servidor Python ejecut치ndose continuamente
# - Base de datos SQLite persistente
# - Procesamiento de archivos
# - Llamadas a API de Google Gemini
#
# Netlify solo soporta sitios est치ticos y funciones serverless limitadas.
#
# 游늷 SOLUCIONES RECOMENDADAS:
#
# 1. RENDER (Recomendado - Gratis para comenzar)
#    - Soporta aplicaciones Python completas
#    - Base de datos incluida
#    - Deploy autom치tico desde GitHub
#    - https://render.com
#
# 2. RAILWAY (Muy f치cil de usar)
#    - Deploy en minutos
#    - $5/mes despu칠s del tier gratuito
#    - https://railway.app
#
# 3. HEROKU (Cl치sico)
#    - Bien documentado
#    - Gratis hasta cierto punto
#    - https://heroku.com
#
# 4. PythonAnywhere (Espec칤fico para Python)
#    - Dise침ado para aplicaciones Python
#    - Plan gratuito disponible
#    - https://pythonanywhere.com
#
# 游닀 Ver DEPLOYMENT_GUIDE.md para instrucciones paso a paso

# Si intentas desplegar aqu칤 de todos modos (NO funcionar치):
[build]
  ignore = "exit 1"  # Detiene el build inmediatamente
  
[build.environment]
  PYTHON_VERSION = "3.11"
  
# Mensaje de error personalizado
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

